# Generated by Django 2.1 on 2022-05-15 12:23

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=200)),
                ('project_content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('project_published', models.DateTimeField(default=datetime.datetime(2022, 5, 15, 12, 23, 56, 641033), verbose_name='date published')),
                ('project_slug', models.CharField(default=1, max_length=200)),
                ('project_image', models.ImageField(blank=True, null=True, upload_to=main.models.get_image_path)),
            ],
        ),
    ]
