# Generated by Django 2.1 on 2022-05-15 13:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_published',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 15, 13, 40, 15, 644822), verbose_name='date published'),
        ),
    ]
